class LaptopModel {
  int id;
  String merk;
  String nama;
  int harga;
  String processor;
  String ram;
  String penyimpanan;
  String grafis;
  String baterai;
  String deskripsi;
  List foto;
  Map bobot;

  LaptopModel(
    this.id,
    this.merk,
    this.nama,
    this.harga,
    this.processor,
    this.ram,
    this.penyimpanan,
    this.grafis,
    this.baterai,
    this.deskripsi,
    this.foto,
    this.bobot,
  );
}

var laptopList = [
  LaptopModel(
      1,
      "ZYREX",
      "ZYREX 232",
      3699000,
      "Intel Apollo Lake N3350 | Dual Core 1.1 - 2.4 GHz",
      "4 GB DDR4",
      "256GB SSD M.2 | 64GB Emmc",
      "Integrated Intel HD Graphics 500 ( 11.6 Inch FHD 1920 x 1080 IPS )",
      "5000 Mah",
      "Acer Chromebook 714 adalah laptop bisnis yang terlihat premium dengan sasis aluminium ramping yang akan meningkatkan aura sopan dan profesional Anda saat Anda membawa perangkat yang disempurnakan ini dari satu rapat kantor ke rapat lainnya.",
      ["assets/laptop_1_1.png","assets/laptop_1_2.png"],
      {"harga": 3, "grafis": 3, "penyimpanan": 3, "baterai": 3, "ram": 3}),
  LaptopModel(
      2,
      "ASUS",
      "ASUS X441MA",
      4799000,
      "Intel Celeron N4020 ( 2 Core | 2 Thread | up to 2.8 Ghz )",
      "4GB DDR 4 up to 8GB Upgradable",
      "1TB 5400RPM SATA HDD",
      "Integrated Intel HD Graphics ( 14\" LED backlit HD 60Hz Glare panel )",
      "3 Cells 36 Whrs",
      "Acer Chromebook 714 adalah laptop bisnis yang terlihat premium dengan sasis aluminium ramping yang akan meningkatkan aura sopan dan profesional Anda saat Anda membawa perangkat yang disempurnakan ini dari satu rapat kantor ke rapat lainnya.",
      ["assets/laptop_2_1.png","assets/laptop_2_2.png"],
      {"harga": 3, "grafis": 3, "penyimpanan": 3, "baterai": 3, "ram": 3}),
  LaptopModel(
      3,
      "DELL",
      "Dell Latitude 11 3190",
      4999000,
      "Intel Pentium Silver N5000 ( 4 Core | 4 Thread | up to 2.7 Ghz )",
      "4GB DDR4",
      "128GB SSD",
      "Integrated Intel HD Graphics ( 11.6 Inch TouchScreen HD )",
      "5000 Mah",
      "Acer Chromebook 714 adalah laptop bisnis yang terlihat premium dengan sasis aluminium ramping yang akan meningkatkan aura sopan dan profesional Anda saat Anda membawa perangkat yang disempurnakan ini dari satu rapat kantor ke rapat lainnya.",
      ["assets/laptop_3_1.png","assets/laptop_3_2.png"],
      {"harga": 3, "grafis": 3, "penyimpanan": 3, "baterai": 3, "ram": 3}),
  LaptopModel(
      4,
      "LENOVO",
      "Lenovo Slim 3 14ADA05",
      4999000,
      "AMD 3020e ( 2C / 2T, 1.2 / 2.6GHz, 1MB L2 / 4MB L3 )",
      "4GB DDR4 2400MHz OnBoard + 1 Slot",
      "256GB PCIe NVMe M.2 SSD",
      "Integrated Radeon ( 14\" HD 1366x768 TN 220nits Anti-glare )",
      "5000 Mah",
      "Acer Chromebook 714 adalah laptop bisnis yang terlihat premium dengan sasis aluminium ramping yang akan meningkatkan aura sopan dan profesional Anda saat Anda membawa perangkat yang disempurnakan ini dari satu rapat kantor ke rapat lainnya.",
      ["assets/laptop_4_1.png","assets/laptop_4_2.png"],
      {"harga": 3, "grafis": 3, "penyimpanan": 3, "baterai": 3, "ram": 3}),
  LaptopModel(
      5,
      "LENOVO",
      "Lenovo Slim 3I-14IGL05",
      5199000,
      "Intel Celeron N4020 ( 2C / 2T, 1.1 / 2.8GHz, 1MB L2 / 4MB L3 )",
      "4GB DDR4 2400MHz OnBoard + 1 Slot",
      "256GB PCIe NVMe M.2 SSD",
      "Integrated Radeon ( 14\" HD 1366x768 TN 220nits Anti-glare )",
      "5000 Mah",
      "Acer Chromebook 714 adalah laptop bisnis yang terlihat premium dengan sasis aluminium ramping yang akan meningkatkan aura sopan dan profesional Anda saat Anda membawa perangkat yang disempurnakan ini dari satu rapat kantor ke rapat lainnya.",
      ["assets/laptop_5_1.png","assets/laptop_5_2.png"],
      {"harga": 3, "grafis": 3, "penyimpanan": 3, "baterai": 3, "ram": 3}),
  LaptopModel(
      6,
      "ACER",
      "Acer Aspire 3 A314 32",
      5299000,
      "Intel Celeron Quad Core N4120 ( 4C / 4T, 1.1 / 2.7GHz, 1MB L2 / 4MB L3 )",
      "4GB DDR4 2400MHz OnBoard + 1 Slot",
      "256GB PCIe NVMe M.2 SSD",
      "Integrated UHD Graphics ( 14\" HD 1366x768 Acer ComfyView )",
      "5000 Mah",
      "Acer Chromebook 714 adalah laptop bisnis yang terlihat premium dengan sasis aluminium ramping yang akan meningkatkan aura sopan dan profesional Anda saat Anda membawa perangkat yang disempurnakan ini dari satu rapat kantor ke rapat lainnya.",
      ["assets/laptop_6_1.png","assets/laptop_6_2.png"],
      {"harga": 3, "grafis": 3, "penyimpanan": 3, "baterai": 3, "ram": 3}),
  LaptopModel(
      7,
      "ACER",
      "Acer Aspire 3 A314 22",
      5999000,
      "AMD Athlon 3050U ( 1MB L2 Cache, 4MB L3 Cache, 2.3GHz up to 3.2GHz )",
      "4 GB DDR4 2400MHz OnBoard + 1 Slot",
      "256GB PCIe NVMe M.2 SSD",
      "AMD Radeon Graphics ( 14\" IPS Panel FHD Acer ComfyView )",
      "5000 Mah",
      "Acer Chromebook 714 adalah laptop bisnis yang terlihat premium dengan sasis aluminium ramping yang akan meningkatkan aura sopan dan profesional Anda saat Anda membawa perangkat yang disempurnakan ini dari satu rapat kantor ke rapat lainnya.",
      ["assets/laptop_7_1.png","assets/laptop_7_2.png"],
      {"harga": 3, "grafis": 3, "penyimpanan": 3, "baterai": 3, "ram": 3}),
  LaptopModel(
      8,
      "LENOVO",
      "Lenovo V14 Athlon Gold",
      5999000,
      "AMD Athlon Gold 3150U ( 2C / 2T, 2.3 / 3.2GHz, 1MB L2 / 4MB L3 )",
      "4 GB DDR4 2400MHz OnBoard + 1 Slot",
      "SSD 256GB M.2 2242 NVME 3.0x2",
      "AMD Radeon Graphics ( 14\" HD 1366x768 TN Anti Glare)",
      "5000 Mah",
      "Acer Chromebook 714 adalah laptop bisnis yang terlihat premium dengan sasis aluminium ramping yang akan meningkatkan aura sopan dan profesional Anda saat Anda membawa perangkat yang disempurnakan ini dari satu rapat kantor ke rapat lainnya.",
      ["assets/laptop_8_1.png","assets/laptop_8_2.png"],
      {"harga": 3, "grafis": 3, "penyimpanan": 3, "baterai": 3, "ram": 3}),
  LaptopModel(
      9,
      "ASUS",
      "ASUS A412FA EK54051T",
      6599000,
      "Intel Pentium Gold 5405U ( 2C / 4T / 2.3GHz, 2MB SmartCache )",
      "4 GB DDR4 2400MHz OnBoard + 1 Slot",
      "256GB SSD Nvme or 1TB HDD",
      "Integrated UHD Graphics ( 14\" Led-backlit FHD 1920x1080 )",
      "5000 Mah",
      "Acer Chromebook 714 adalah laptop bisnis yang terlihat premium dengan sasis aluminium ramping yang akan meningkatkan aura sopan dan profesional Anda saat Anda membawa perangkat yang disempurnakan ini dari satu rapat kantor ke rapat lainnya.",
      ["assets/laptop_9_1.png","assets/laptop_9_2.png"],
      {"harga": 3, "grafis": 3, "penyimpanan": 3, "baterai": 3, "ram": 3}),
  LaptopModel(
      10,
      "ACER",
      "Acer Aspire 3 Slim A314-22",
      6999000,
      "AMD Ryzen 3-3250U ( 1MB L2 Cache, 4MB L3 Cache, 2.6GHz up to 3.5 GHz )",
      "4GB DDR4 2400MHz OnBoard extra 1 Slot",
      "256GB PCIe NVMe M.2 SSD",
      "Integrated UHD Graphics ( 14 Inch Full HD 1920 x 1080 Acer ComfyView )",
      "5000 Mah",
      "Acer Chromebook 714 adalah laptop bisnis yang terlihat premium dengan sasis aluminium ramping yang akan meningkatkan aura sopan dan profesional Anda saat Anda membawa perangkat yang disempurnakan ini dari satu rapat kantor ke rapat lainnya.",
      ["assets/laptop_10_1.png","assets/laptop_10_2.png"],
      {"harga": 3, "grafis": 3, "penyimpanan": 3, "baterai": 3, "ram": 3}),
  LaptopModel(
      11,
      "LENOVO",
      "Lenovo Slim 3I I3-1005G1",
      7999000,
      "Intel Core i3-1005G1 ( 2 C, 2 T | 1.2 - 3.4 Ghz | 4 MB L3 )",
      "4GB DDR4 2666Hz ",
      "512GB SSD M.2 2242 PCIe NVMe 3.0x2",
      "Integrated Graphics ( 14 Inch FHD WVA 250nits Anti-glare )",
      "5000 Mah",
      "Acer Chromebook 714 adalah laptop bisnis yang terlihat premium dengan sasis aluminium ramping yang akan meningkatkan aura sopan dan profesional Anda saat Anda membawa perangkat yang disempurnakan ini dari satu rapat kantor ke rapat lainnya.",
      ["assets/laptop_11_1.png","assets/laptop_11_2.png"],
      {"harga": 3, "grafis": 3, "penyimpanan": 3, "baterai": 3, "ram": 3}),
  LaptopModel(
      12,
      "ACER",
      "Acer Aspire 5 A514",
      7899000,
      "Intel Core i3-1005G1 ( 2 C, 2 T | 1.2 - 3.4 Ghz | 4 MB L3 )",
      "4GB DDR4 2666Hz ",
      "512GB SSD M.2 2242 PCIe NVMe 3.0x2",
      "Integrated Graphics ( 14 Inch HD WVA 1366 x 768 Acer ComfyView )",
      "5000 Mah",
      "Acer Chromebook 714 adalah laptop bisnis yang terlihat premium dengan sasis aluminium ramping yang akan meningkatkan aura sopan dan profesional Anda saat Anda membawa perangkat yang disempurnakan ini dari satu rapat kantor ke rapat lainnya.",
      ["assets/laptop_12_1.png","assets/laptop_12_2.png"],
      {"harga": 3, "grafis": 3, "penyimpanan": 3, "baterai": 3, "ram": 3}),
];
